---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gofe-securityspy
  namespace: services
  labels:
    app: securityspy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: securityspy
  template:
    metadata:
      labels:
        app: securityspy
    spec:
      containers:
      - name: gofe-securityspy
        image: garybowers/gofe:0.3
        ports:
        - name: gofe
          protocol: TCP
          containerPort: 9090
        env:
        - name: "BACKEND"
          value: "http://10.76.42.1:8000"
---
apiVersion: v1
kind: Service
metadata:
  name: gofe-securityspy 
  namespace: services
  labels:
    app: securityspy
spec:
  selector:
    app: securityspy
  ports:
  - name: tcp-gofe-securityspy
    port: 80
    targetPort: 9090
    protocol: TCP
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: gofe-securityspy-vs 
  namespace: istio-system
spec:
  gateways:
  - ingress-gateway
  hosts:
  - securityspy.bowers1.com
  http:
  - match:
    - uri:
        prefix: "/"
    route: 
    - destination:
        host: gofe-securityspy.services.svc.cluster.local 
        port:
          number: 80
